version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      tanstack:
        patterns:
          - '@tanstack/*'
      orpc:
        patterns:
          - '@orpc/*'
      electron:
        patterns:
          - 'electron'
          - 'electron-builder'
          - 'vite-plugin-electron*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
