projects:
  globs:
    - 'apps/*'
  sources:
    root: '.'

vcs:
  defaultBranch: 'main'
  provider: 'github'
  hooks:
    pre-commit:
      - 'prettier --write --ignore-unknown $(git diff --cached --name-only --diff-filter=ACMR) && git update-index --again'
      - 'moon run :lint :typecheck --affected --status=staged'
  sync: true

pipeline:
  logRunningCommand: true
