projects:
  globs:
    - 'apps/*'
  sources:
    root: '.'

vcs:
  defaultBranch: 'main'
  provider: 'github'
  hooks:
    pre-commit:
      - 'moon run :lint :typecheck --affected --status=staged'
  sync: true

pipeline:
  logRunningCommand: true
