/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardLogsIndexRouteImport } from './routes/dashboard/logs/index'
import { Route as DashboardGatewaysIndexRouteImport } from './routes/dashboard/gateways/index'
import { Route as DashboardGatewaysGatewayIdRouteRouteImport } from './routes/dashboard/gateways/$gatewayId/route'
import { Route as DashboardGatewaysGatewayIdIndexRouteImport } from './routes/dashboard/gateways/$gatewayId/index'
import { Route as DashboardGatewaysGatewayIdUsageRouteImport } from './routes/dashboard/gateways/$gatewayId/usage'
import { Route as DashboardGatewaysGatewayIdSkillsRouteImport } from './routes/dashboard/gateways/$gatewayId/skills'
import { Route as DashboardGatewaysGatewayIdSecurityRouteImport } from './routes/dashboard/gateways/$gatewayId/security'
import { Route as DashboardGatewaysGatewayIdNodesRouteImport } from './routes/dashboard/gateways/$gatewayId/nodes'
import { Route as DashboardGatewaysGatewayIdModelsRouteImport } from './routes/dashboard/gateways/$gatewayId/models'
import { Route as DashboardGatewaysGatewayIdLogsRouteImport } from './routes/dashboard/gateways/$gatewayId/logs'
import { Route as DashboardGatewaysGatewayIdHealthRouteImport } from './routes/dashboard/gateways/$gatewayId/health'
import { Route as DashboardGatewaysGatewayIdDevicesRouteImport } from './routes/dashboard/gateways/$gatewayId/devices'
import { Route as DashboardGatewaysGatewayIdCronRouteImport } from './routes/dashboard/gateways/$gatewayId/cron'
import { Route as DashboardGatewaysGatewayIdConfigRouteImport } from './routes/dashboard/gateways/$gatewayId/config'
import { Route as DashboardGatewaysGatewayIdChatRouteImport } from './routes/dashboard/gateways/$gatewayId/chat'
import { Route as DashboardGatewaysGatewayIdChannelsRouteImport } from './routes/dashboard/gateways/$gatewayId/channels'
import { Route as DashboardGatewaysGatewayIdAgentsRouteImport } from './routes/dashboard/gateways/$gatewayId/agents'
import { Route as DashboardGatewaysGatewayIdSessionsIndexRouteImport } from './routes/dashboard/gateways/$gatewayId/sessions/index'
import { Route as DashboardGatewaysGatewayIdSessionsSessionKeyRouteImport } from './routes/dashboard/gateways/$gatewayId_.sessions.$sessionKey'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLogsIndexRoute = DashboardLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGatewaysIndexRoute = DashboardGatewaysIndexRouteImport.update({
  id: '/gateways/',
  path: '/gateways/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGatewaysGatewayIdRouteRoute =
  DashboardGatewaysGatewayIdRouteRouteImport.update({
    id: '/gateways/$gatewayId',
    path: '/gateways/$gatewayId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardGatewaysGatewayIdIndexRoute =
  DashboardGatewaysGatewayIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardGatewaysGatewayIdRouteRoute,
  } as any)
const DashboardGatewaysGatewayIdUsageRoute =
  DashboardGatewaysGatewayIdUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => DashboardGatewaysGatewayIdRouteRoute,
  } as any)
const DashboardGatewaysGatewayIdSkillsRoute =
  DashboardGatewaysGatewayIdSkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => DashboardGatewaysGatewayIdRouteRoute,
  } as any)
const DashboardGatewaysGatewayIdSecurityRoute =
  DashboardGatewaysGatewayIdSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => DashboardGatewaysGatewayIdRouteRoute,
  } as any)
const DashboardGatewaysGatewayIdNodesRoute =
  DashboardGatewaysGatewayIdNodesRouteImport.update({
    id: '/nodes',
    path: '/nodes',
    getParentRoute: () => DashboardGatewaysGatewayIdRouteRoute,
  } as any)
const DashboardGatewaysGatewayIdModelsRoute =
  DashboardGatewaysGatewayIdModelsRouteImport.update({
    id: '/models',
    path: '/models',
    getParentRoute: () => DashboardGatewaysGatewayIdRouteRoute,
  } as any)
const DashboardGatewaysGatewayIdLogsRoute =
  DashboardGatewaysGatewayIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => DashboardGatewaysGatewayIdRouteRoute,
  } as any)
const DashboardGatewaysGatewayIdHealthRoute =
  DashboardGatewaysGatewayIdHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => DashboardGatewaysGatewayIdRouteRoute,
  } as any)
const DashboardGatewaysGatewayIdDevicesRoute =
  DashboardGatewaysGatewayIdDevicesRouteImport.update({
    id: '/devices',
    path: '/devices',
    getParentRoute: () => DashboardGatewaysGatewayIdRouteRoute,
  } as any)
const DashboardGatewaysGatewayIdCronRoute =
  DashboardGatewaysGatewayIdCronRouteImport.update({
    id: '/cron',
    path: '/cron',
    getParentRoute: () => DashboardGatewaysGatewayIdRouteRoute,
  } as any)
const DashboardGatewaysGatewayIdConfigRoute =
  DashboardGatewaysGatewayIdConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => DashboardGatewaysGatewayIdRouteRoute,
  } as any)
const DashboardGatewaysGatewayIdChatRoute =
  DashboardGatewaysGatewayIdChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => DashboardGatewaysGatewayIdRouteRoute,
  } as any)
const DashboardGatewaysGatewayIdChannelsRoute =
  DashboardGatewaysGatewayIdChannelsRouteImport.update({
    id: '/channels',
    path: '/channels',
    getParentRoute: () => DashboardGatewaysGatewayIdRouteRoute,
  } as any)
const DashboardGatewaysGatewayIdAgentsRoute =
  DashboardGatewaysGatewayIdAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => DashboardGatewaysGatewayIdRouteRoute,
  } as any)
const DashboardGatewaysGatewayIdSessionsIndexRoute =
  DashboardGatewaysGatewayIdSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => DashboardGatewaysGatewayIdRouteRoute,
  } as any)
const DashboardGatewaysGatewayIdSessionsSessionKeyRoute =
  DashboardGatewaysGatewayIdSessionsSessionKeyRouteImport.update({
    id: '/gateways/$gatewayId_/sessions/$sessionKey',
    path: '/gateways/$gatewayId/sessions/$sessionKey',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/gateways/$gatewayId': typeof DashboardGatewaysGatewayIdRouteRouteWithChildren
  '/dashboard/gateways/': typeof DashboardGatewaysIndexRoute
  '/dashboard/logs/': typeof DashboardLogsIndexRoute
  '/dashboard/gateways/$gatewayId/agents': typeof DashboardGatewaysGatewayIdAgentsRoute
  '/dashboard/gateways/$gatewayId/channels': typeof DashboardGatewaysGatewayIdChannelsRoute
  '/dashboard/gateways/$gatewayId/chat': typeof DashboardGatewaysGatewayIdChatRoute
  '/dashboard/gateways/$gatewayId/config': typeof DashboardGatewaysGatewayIdConfigRoute
  '/dashboard/gateways/$gatewayId/cron': typeof DashboardGatewaysGatewayIdCronRoute
  '/dashboard/gateways/$gatewayId/devices': typeof DashboardGatewaysGatewayIdDevicesRoute
  '/dashboard/gateways/$gatewayId/health': typeof DashboardGatewaysGatewayIdHealthRoute
  '/dashboard/gateways/$gatewayId/logs': typeof DashboardGatewaysGatewayIdLogsRoute
  '/dashboard/gateways/$gatewayId/models': typeof DashboardGatewaysGatewayIdModelsRoute
  '/dashboard/gateways/$gatewayId/nodes': typeof DashboardGatewaysGatewayIdNodesRoute
  '/dashboard/gateways/$gatewayId/security': typeof DashboardGatewaysGatewayIdSecurityRoute
  '/dashboard/gateways/$gatewayId/skills': typeof DashboardGatewaysGatewayIdSkillsRoute
  '/dashboard/gateways/$gatewayId/usage': typeof DashboardGatewaysGatewayIdUsageRoute
  '/dashboard/gateways/$gatewayId/': typeof DashboardGatewaysGatewayIdIndexRoute
  '/dashboard/gateways/$gatewayId/sessions/$sessionKey': typeof DashboardGatewaysGatewayIdSessionsSessionKeyRoute
  '/dashboard/gateways/$gatewayId/sessions/': typeof DashboardGatewaysGatewayIdSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/gateways': typeof DashboardGatewaysIndexRoute
  '/dashboard/logs': typeof DashboardLogsIndexRoute
  '/dashboard/gateways/$gatewayId/agents': typeof DashboardGatewaysGatewayIdAgentsRoute
  '/dashboard/gateways/$gatewayId/channels': typeof DashboardGatewaysGatewayIdChannelsRoute
  '/dashboard/gateways/$gatewayId/chat': typeof DashboardGatewaysGatewayIdChatRoute
  '/dashboard/gateways/$gatewayId/config': typeof DashboardGatewaysGatewayIdConfigRoute
  '/dashboard/gateways/$gatewayId/cron': typeof DashboardGatewaysGatewayIdCronRoute
  '/dashboard/gateways/$gatewayId/devices': typeof DashboardGatewaysGatewayIdDevicesRoute
  '/dashboard/gateways/$gatewayId/health': typeof DashboardGatewaysGatewayIdHealthRoute
  '/dashboard/gateways/$gatewayId/logs': typeof DashboardGatewaysGatewayIdLogsRoute
  '/dashboard/gateways/$gatewayId/models': typeof DashboardGatewaysGatewayIdModelsRoute
  '/dashboard/gateways/$gatewayId/nodes': typeof DashboardGatewaysGatewayIdNodesRoute
  '/dashboard/gateways/$gatewayId/security': typeof DashboardGatewaysGatewayIdSecurityRoute
  '/dashboard/gateways/$gatewayId/skills': typeof DashboardGatewaysGatewayIdSkillsRoute
  '/dashboard/gateways/$gatewayId/usage': typeof DashboardGatewaysGatewayIdUsageRoute
  '/dashboard/gateways/$gatewayId': typeof DashboardGatewaysGatewayIdIndexRoute
  '/dashboard/gateways/$gatewayId/sessions/$sessionKey': typeof DashboardGatewaysGatewayIdSessionsSessionKeyRoute
  '/dashboard/gateways/$gatewayId/sessions': typeof DashboardGatewaysGatewayIdSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/gateways/$gatewayId': typeof DashboardGatewaysGatewayIdRouteRouteWithChildren
  '/dashboard/gateways/': typeof DashboardGatewaysIndexRoute
  '/dashboard/logs/': typeof DashboardLogsIndexRoute
  '/dashboard/gateways/$gatewayId/agents': typeof DashboardGatewaysGatewayIdAgentsRoute
  '/dashboard/gateways/$gatewayId/channels': typeof DashboardGatewaysGatewayIdChannelsRoute
  '/dashboard/gateways/$gatewayId/chat': typeof DashboardGatewaysGatewayIdChatRoute
  '/dashboard/gateways/$gatewayId/config': typeof DashboardGatewaysGatewayIdConfigRoute
  '/dashboard/gateways/$gatewayId/cron': typeof DashboardGatewaysGatewayIdCronRoute
  '/dashboard/gateways/$gatewayId/devices': typeof DashboardGatewaysGatewayIdDevicesRoute
  '/dashboard/gateways/$gatewayId/health': typeof DashboardGatewaysGatewayIdHealthRoute
  '/dashboard/gateways/$gatewayId/logs': typeof DashboardGatewaysGatewayIdLogsRoute
  '/dashboard/gateways/$gatewayId/models': typeof DashboardGatewaysGatewayIdModelsRoute
  '/dashboard/gateways/$gatewayId/nodes': typeof DashboardGatewaysGatewayIdNodesRoute
  '/dashboard/gateways/$gatewayId/security': typeof DashboardGatewaysGatewayIdSecurityRoute
  '/dashboard/gateways/$gatewayId/skills': typeof DashboardGatewaysGatewayIdSkillsRoute
  '/dashboard/gateways/$gatewayId/usage': typeof DashboardGatewaysGatewayIdUsageRoute
  '/dashboard/gateways/$gatewayId/': typeof DashboardGatewaysGatewayIdIndexRoute
  '/dashboard/gateways/$gatewayId_/sessions/$sessionKey': typeof DashboardGatewaysGatewayIdSessionsSessionKeyRoute
  '/dashboard/gateways/$gatewayId/sessions/': typeof DashboardGatewaysGatewayIdSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/gateways/$gatewayId'
    | '/dashboard/gateways/'
    | '/dashboard/logs/'
    | '/dashboard/gateways/$gatewayId/agents'
    | '/dashboard/gateways/$gatewayId/channels'
    | '/dashboard/gateways/$gatewayId/chat'
    | '/dashboard/gateways/$gatewayId/config'
    | '/dashboard/gateways/$gatewayId/cron'
    | '/dashboard/gateways/$gatewayId/devices'
    | '/dashboard/gateways/$gatewayId/health'
    | '/dashboard/gateways/$gatewayId/logs'
    | '/dashboard/gateways/$gatewayId/models'
    | '/dashboard/gateways/$gatewayId/nodes'
    | '/dashboard/gateways/$gatewayId/security'
    | '/dashboard/gateways/$gatewayId/skills'
    | '/dashboard/gateways/$gatewayId/usage'
    | '/dashboard/gateways/$gatewayId/'
    | '/dashboard/gateways/$gatewayId/sessions/$sessionKey'
    | '/dashboard/gateways/$gatewayId/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/gateways'
    | '/dashboard/logs'
    | '/dashboard/gateways/$gatewayId/agents'
    | '/dashboard/gateways/$gatewayId/channels'
    | '/dashboard/gateways/$gatewayId/chat'
    | '/dashboard/gateways/$gatewayId/config'
    | '/dashboard/gateways/$gatewayId/cron'
    | '/dashboard/gateways/$gatewayId/devices'
    | '/dashboard/gateways/$gatewayId/health'
    | '/dashboard/gateways/$gatewayId/logs'
    | '/dashboard/gateways/$gatewayId/models'
    | '/dashboard/gateways/$gatewayId/nodes'
    | '/dashboard/gateways/$gatewayId/security'
    | '/dashboard/gateways/$gatewayId/skills'
    | '/dashboard/gateways/$gatewayId/usage'
    | '/dashboard/gateways/$gatewayId'
    | '/dashboard/gateways/$gatewayId/sessions/$sessionKey'
    | '/dashboard/gateways/$gatewayId/sessions'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/gateways/$gatewayId'
    | '/dashboard/gateways/'
    | '/dashboard/logs/'
    | '/dashboard/gateways/$gatewayId/agents'
    | '/dashboard/gateways/$gatewayId/channels'
    | '/dashboard/gateways/$gatewayId/chat'
    | '/dashboard/gateways/$gatewayId/config'
    | '/dashboard/gateways/$gatewayId/cron'
    | '/dashboard/gateways/$gatewayId/devices'
    | '/dashboard/gateways/$gatewayId/health'
    | '/dashboard/gateways/$gatewayId/logs'
    | '/dashboard/gateways/$gatewayId/models'
    | '/dashboard/gateways/$gatewayId/nodes'
    | '/dashboard/gateways/$gatewayId/security'
    | '/dashboard/gateways/$gatewayId/skills'
    | '/dashboard/gateways/$gatewayId/usage'
    | '/dashboard/gateways/$gatewayId/'
    | '/dashboard/gateways/$gatewayId_/sessions/$sessionKey'
    | '/dashboard/gateways/$gatewayId/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/logs/': {
      id: '/dashboard/logs/'
      path: '/logs'
      fullPath: '/dashboard/logs/'
      preLoaderRoute: typeof DashboardLogsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/gateways/': {
      id: '/dashboard/gateways/'
      path: '/gateways'
      fullPath: '/dashboard/gateways/'
      preLoaderRoute: typeof DashboardGatewaysIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/gateways/$gatewayId': {
      id: '/dashboard/gateways/$gatewayId'
      path: '/gateways/$gatewayId'
      fullPath: '/dashboard/gateways/$gatewayId'
      preLoaderRoute: typeof DashboardGatewaysGatewayIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/gateways/$gatewayId/': {
      id: '/dashboard/gateways/$gatewayId/'
      path: '/'
      fullPath: '/dashboard/gateways/$gatewayId/'
      preLoaderRoute: typeof DashboardGatewaysGatewayIdIndexRouteImport
      parentRoute: typeof DashboardGatewaysGatewayIdRouteRoute
    }
    '/dashboard/gateways/$gatewayId/usage': {
      id: '/dashboard/gateways/$gatewayId/usage'
      path: '/usage'
      fullPath: '/dashboard/gateways/$gatewayId/usage'
      preLoaderRoute: typeof DashboardGatewaysGatewayIdUsageRouteImport
      parentRoute: typeof DashboardGatewaysGatewayIdRouteRoute
    }
    '/dashboard/gateways/$gatewayId/skills': {
      id: '/dashboard/gateways/$gatewayId/skills'
      path: '/skills'
      fullPath: '/dashboard/gateways/$gatewayId/skills'
      preLoaderRoute: typeof DashboardGatewaysGatewayIdSkillsRouteImport
      parentRoute: typeof DashboardGatewaysGatewayIdRouteRoute
    }
    '/dashboard/gateways/$gatewayId/security': {
      id: '/dashboard/gateways/$gatewayId/security'
      path: '/security'
      fullPath: '/dashboard/gateways/$gatewayId/security'
      preLoaderRoute: typeof DashboardGatewaysGatewayIdSecurityRouteImport
      parentRoute: typeof DashboardGatewaysGatewayIdRouteRoute
    }
    '/dashboard/gateways/$gatewayId/nodes': {
      id: '/dashboard/gateways/$gatewayId/nodes'
      path: '/nodes'
      fullPath: '/dashboard/gateways/$gatewayId/nodes'
      preLoaderRoute: typeof DashboardGatewaysGatewayIdNodesRouteImport
      parentRoute: typeof DashboardGatewaysGatewayIdRouteRoute
    }
    '/dashboard/gateways/$gatewayId/models': {
      id: '/dashboard/gateways/$gatewayId/models'
      path: '/models'
      fullPath: '/dashboard/gateways/$gatewayId/models'
      preLoaderRoute: typeof DashboardGatewaysGatewayIdModelsRouteImport
      parentRoute: typeof DashboardGatewaysGatewayIdRouteRoute
    }
    '/dashboard/gateways/$gatewayId/logs': {
      id: '/dashboard/gateways/$gatewayId/logs'
      path: '/logs'
      fullPath: '/dashboard/gateways/$gatewayId/logs'
      preLoaderRoute: typeof DashboardGatewaysGatewayIdLogsRouteImport
      parentRoute: typeof DashboardGatewaysGatewayIdRouteRoute
    }
    '/dashboard/gateways/$gatewayId/health': {
      id: '/dashboard/gateways/$gatewayId/health'
      path: '/health'
      fullPath: '/dashboard/gateways/$gatewayId/health'
      preLoaderRoute: typeof DashboardGatewaysGatewayIdHealthRouteImport
      parentRoute: typeof DashboardGatewaysGatewayIdRouteRoute
    }
    '/dashboard/gateways/$gatewayId/devices': {
      id: '/dashboard/gateways/$gatewayId/devices'
      path: '/devices'
      fullPath: '/dashboard/gateways/$gatewayId/devices'
      preLoaderRoute: typeof DashboardGatewaysGatewayIdDevicesRouteImport
      parentRoute: typeof DashboardGatewaysGatewayIdRouteRoute
    }
    '/dashboard/gateways/$gatewayId/cron': {
      id: '/dashboard/gateways/$gatewayId/cron'
      path: '/cron'
      fullPath: '/dashboard/gateways/$gatewayId/cron'
      preLoaderRoute: typeof DashboardGatewaysGatewayIdCronRouteImport
      parentRoute: typeof DashboardGatewaysGatewayIdRouteRoute
    }
    '/dashboard/gateways/$gatewayId/config': {
      id: '/dashboard/gateways/$gatewayId/config'
      path: '/config'
      fullPath: '/dashboard/gateways/$gatewayId/config'
      preLoaderRoute: typeof DashboardGatewaysGatewayIdConfigRouteImport
      parentRoute: typeof DashboardGatewaysGatewayIdRouteRoute
    }
    '/dashboard/gateways/$gatewayId/chat': {
      id: '/dashboard/gateways/$gatewayId/chat'
      path: '/chat'
      fullPath: '/dashboard/gateways/$gatewayId/chat'
      preLoaderRoute: typeof DashboardGatewaysGatewayIdChatRouteImport
      parentRoute: typeof DashboardGatewaysGatewayIdRouteRoute
    }
    '/dashboard/gateways/$gatewayId/channels': {
      id: '/dashboard/gateways/$gatewayId/channels'
      path: '/channels'
      fullPath: '/dashboard/gateways/$gatewayId/channels'
      preLoaderRoute: typeof DashboardGatewaysGatewayIdChannelsRouteImport
      parentRoute: typeof DashboardGatewaysGatewayIdRouteRoute
    }
    '/dashboard/gateways/$gatewayId/agents': {
      id: '/dashboard/gateways/$gatewayId/agents'
      path: '/agents'
      fullPath: '/dashboard/gateways/$gatewayId/agents'
      preLoaderRoute: typeof DashboardGatewaysGatewayIdAgentsRouteImport
      parentRoute: typeof DashboardGatewaysGatewayIdRouteRoute
    }
    '/dashboard/gateways/$gatewayId/sessions/': {
      id: '/dashboard/gateways/$gatewayId/sessions/'
      path: '/sessions'
      fullPath: '/dashboard/gateways/$gatewayId/sessions/'
      preLoaderRoute: typeof DashboardGatewaysGatewayIdSessionsIndexRouteImport
      parentRoute: typeof DashboardGatewaysGatewayIdRouteRoute
    }
    '/dashboard/gateways/$gatewayId_/sessions/$sessionKey': {
      id: '/dashboard/gateways/$gatewayId_/sessions/$sessionKey'
      path: '/gateways/$gatewayId/sessions/$sessionKey'
      fullPath: '/dashboard/gateways/$gatewayId/sessions/$sessionKey'
      preLoaderRoute: typeof DashboardGatewaysGatewayIdSessionsSessionKeyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardGatewaysGatewayIdRouteRouteChildren {
  DashboardGatewaysGatewayIdAgentsRoute: typeof DashboardGatewaysGatewayIdAgentsRoute
  DashboardGatewaysGatewayIdChannelsRoute: typeof DashboardGatewaysGatewayIdChannelsRoute
  DashboardGatewaysGatewayIdChatRoute: typeof DashboardGatewaysGatewayIdChatRoute
  DashboardGatewaysGatewayIdConfigRoute: typeof DashboardGatewaysGatewayIdConfigRoute
  DashboardGatewaysGatewayIdCronRoute: typeof DashboardGatewaysGatewayIdCronRoute
  DashboardGatewaysGatewayIdDevicesRoute: typeof DashboardGatewaysGatewayIdDevicesRoute
  DashboardGatewaysGatewayIdHealthRoute: typeof DashboardGatewaysGatewayIdHealthRoute
  DashboardGatewaysGatewayIdLogsRoute: typeof DashboardGatewaysGatewayIdLogsRoute
  DashboardGatewaysGatewayIdModelsRoute: typeof DashboardGatewaysGatewayIdModelsRoute
  DashboardGatewaysGatewayIdNodesRoute: typeof DashboardGatewaysGatewayIdNodesRoute
  DashboardGatewaysGatewayIdSecurityRoute: typeof DashboardGatewaysGatewayIdSecurityRoute
  DashboardGatewaysGatewayIdSkillsRoute: typeof DashboardGatewaysGatewayIdSkillsRoute
  DashboardGatewaysGatewayIdUsageRoute: typeof DashboardGatewaysGatewayIdUsageRoute
  DashboardGatewaysGatewayIdIndexRoute: typeof DashboardGatewaysGatewayIdIndexRoute
  DashboardGatewaysGatewayIdSessionsIndexRoute: typeof DashboardGatewaysGatewayIdSessionsIndexRoute
}

const DashboardGatewaysGatewayIdRouteRouteChildren: DashboardGatewaysGatewayIdRouteRouteChildren =
  {
    DashboardGatewaysGatewayIdAgentsRoute:
      DashboardGatewaysGatewayIdAgentsRoute,
    DashboardGatewaysGatewayIdChannelsRoute:
      DashboardGatewaysGatewayIdChannelsRoute,
    DashboardGatewaysGatewayIdChatRoute: DashboardGatewaysGatewayIdChatRoute,
    DashboardGatewaysGatewayIdConfigRoute:
      DashboardGatewaysGatewayIdConfigRoute,
    DashboardGatewaysGatewayIdCronRoute: DashboardGatewaysGatewayIdCronRoute,
    DashboardGatewaysGatewayIdDevicesRoute:
      DashboardGatewaysGatewayIdDevicesRoute,
    DashboardGatewaysGatewayIdHealthRoute:
      DashboardGatewaysGatewayIdHealthRoute,
    DashboardGatewaysGatewayIdLogsRoute: DashboardGatewaysGatewayIdLogsRoute,
    DashboardGatewaysGatewayIdModelsRoute:
      DashboardGatewaysGatewayIdModelsRoute,
    DashboardGatewaysGatewayIdNodesRoute: DashboardGatewaysGatewayIdNodesRoute,
    DashboardGatewaysGatewayIdSecurityRoute:
      DashboardGatewaysGatewayIdSecurityRoute,
    DashboardGatewaysGatewayIdSkillsRoute:
      DashboardGatewaysGatewayIdSkillsRoute,
    DashboardGatewaysGatewayIdUsageRoute: DashboardGatewaysGatewayIdUsageRoute,
    DashboardGatewaysGatewayIdIndexRoute: DashboardGatewaysGatewayIdIndexRoute,
    DashboardGatewaysGatewayIdSessionsIndexRoute:
      DashboardGatewaysGatewayIdSessionsIndexRoute,
  }

const DashboardGatewaysGatewayIdRouteRouteWithChildren =
  DashboardGatewaysGatewayIdRouteRoute._addFileChildren(
    DashboardGatewaysGatewayIdRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardGatewaysGatewayIdRouteRoute: typeof DashboardGatewaysGatewayIdRouteRouteWithChildren
  DashboardGatewaysIndexRoute: typeof DashboardGatewaysIndexRoute
  DashboardLogsIndexRoute: typeof DashboardLogsIndexRoute
  DashboardGatewaysGatewayIdSessionsSessionKeyRoute: typeof DashboardGatewaysGatewayIdSessionsSessionKeyRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardGatewaysGatewayIdRouteRoute:
    DashboardGatewaysGatewayIdRouteRouteWithChildren,
  DashboardGatewaysIndexRoute: DashboardGatewaysIndexRoute,
  DashboardLogsIndexRoute: DashboardLogsIndexRoute,
  DashboardGatewaysGatewayIdSessionsSessionKeyRoute:
    DashboardGatewaysGatewayIdSessionsSessionKeyRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
