/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardLogsIndexRouteImport } from './routes/dashboard/logs/index'
import { Route as DashboardGatewaysIndexRouteImport } from './routes/dashboard/gateways/index'
import { Route as DashboardGatewaysGatewayIdRouteRouteImport } from './routes/dashboard/gateways/$gatewayId/route'
import { Route as DashboardGatewaysGatewayIdIndexRouteImport } from './routes/dashboard/gateways/$gatewayId/index'
import { Route as DashboardGatewaysGatewayIdSettingsRouteImport } from './routes/dashboard/gateways/$gatewayId/settings'
import { Route as DashboardGatewaysGatewayIdSessionsIndexRouteImport } from './routes/dashboard/gateways/$gatewayId/sessions/index'
import { Route as DashboardGatewaysGatewayIdSessionsSessionKeyRouteImport } from './routes/dashboard/gateways/$gatewayId_.sessions.$sessionKey'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLogsIndexRoute = DashboardLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGatewaysIndexRoute = DashboardGatewaysIndexRouteImport.update({
  id: '/gateways/',
  path: '/gateways/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGatewaysGatewayIdRouteRoute =
  DashboardGatewaysGatewayIdRouteRouteImport.update({
    id: '/gateways/$gatewayId',
    path: '/gateways/$gatewayId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardGatewaysGatewayIdIndexRoute =
  DashboardGatewaysGatewayIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardGatewaysGatewayIdRouteRoute,
  } as any)
const DashboardGatewaysGatewayIdSettingsRoute =
  DashboardGatewaysGatewayIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardGatewaysGatewayIdRouteRoute,
  } as any)
const DashboardGatewaysGatewayIdSessionsIndexRoute =
  DashboardGatewaysGatewayIdSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => DashboardGatewaysGatewayIdRouteRoute,
  } as any)
const DashboardGatewaysGatewayIdSessionsSessionKeyRoute =
  DashboardGatewaysGatewayIdSessionsSessionKeyRouteImport.update({
    id: '/gateways/$gatewayId_/sessions/$sessionKey',
    path: '/gateways/$gatewayId/sessions/$sessionKey',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/gateways/$gatewayId': typeof DashboardGatewaysGatewayIdRouteRouteWithChildren
  '/dashboard/gateways/': typeof DashboardGatewaysIndexRoute
  '/dashboard/logs/': typeof DashboardLogsIndexRoute
  '/dashboard/gateways/$gatewayId/settings': typeof DashboardGatewaysGatewayIdSettingsRoute
  '/dashboard/gateways/$gatewayId/': typeof DashboardGatewaysGatewayIdIndexRoute
  '/dashboard/gateways/$gatewayId/sessions/$sessionKey': typeof DashboardGatewaysGatewayIdSessionsSessionKeyRoute
  '/dashboard/gateways/$gatewayId/sessions/': typeof DashboardGatewaysGatewayIdSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/gateways': typeof DashboardGatewaysIndexRoute
  '/dashboard/logs': typeof DashboardLogsIndexRoute
  '/dashboard/gateways/$gatewayId/settings': typeof DashboardGatewaysGatewayIdSettingsRoute
  '/dashboard/gateways/$gatewayId': typeof DashboardGatewaysGatewayIdIndexRoute
  '/dashboard/gateways/$gatewayId/sessions/$sessionKey': typeof DashboardGatewaysGatewayIdSessionsSessionKeyRoute
  '/dashboard/gateways/$gatewayId/sessions': typeof DashboardGatewaysGatewayIdSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/gateways/$gatewayId': typeof DashboardGatewaysGatewayIdRouteRouteWithChildren
  '/dashboard/gateways/': typeof DashboardGatewaysIndexRoute
  '/dashboard/logs/': typeof DashboardLogsIndexRoute
  '/dashboard/gateways/$gatewayId/settings': typeof DashboardGatewaysGatewayIdSettingsRoute
  '/dashboard/gateways/$gatewayId/': typeof DashboardGatewaysGatewayIdIndexRoute
  '/dashboard/gateways/$gatewayId_/sessions/$sessionKey': typeof DashboardGatewaysGatewayIdSessionsSessionKeyRoute
  '/dashboard/gateways/$gatewayId/sessions/': typeof DashboardGatewaysGatewayIdSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/gateways/$gatewayId'
    | '/dashboard/gateways/'
    | '/dashboard/logs/'
    | '/dashboard/gateways/$gatewayId/settings'
    | '/dashboard/gateways/$gatewayId/'
    | '/dashboard/gateways/$gatewayId/sessions/$sessionKey'
    | '/dashboard/gateways/$gatewayId/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/gateways'
    | '/dashboard/logs'
    | '/dashboard/gateways/$gatewayId/settings'
    | '/dashboard/gateways/$gatewayId'
    | '/dashboard/gateways/$gatewayId/sessions/$sessionKey'
    | '/dashboard/gateways/$gatewayId/sessions'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/gateways/$gatewayId'
    | '/dashboard/gateways/'
    | '/dashboard/logs/'
    | '/dashboard/gateways/$gatewayId/settings'
    | '/dashboard/gateways/$gatewayId/'
    | '/dashboard/gateways/$gatewayId_/sessions/$sessionKey'
    | '/dashboard/gateways/$gatewayId/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/logs/': {
      id: '/dashboard/logs/'
      path: '/logs'
      fullPath: '/dashboard/logs/'
      preLoaderRoute: typeof DashboardLogsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/gateways/': {
      id: '/dashboard/gateways/'
      path: '/gateways'
      fullPath: '/dashboard/gateways/'
      preLoaderRoute: typeof DashboardGatewaysIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/gateways/$gatewayId': {
      id: '/dashboard/gateways/$gatewayId'
      path: '/gateways/$gatewayId'
      fullPath: '/dashboard/gateways/$gatewayId'
      preLoaderRoute: typeof DashboardGatewaysGatewayIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/gateways/$gatewayId/': {
      id: '/dashboard/gateways/$gatewayId/'
      path: '/'
      fullPath: '/dashboard/gateways/$gatewayId/'
      preLoaderRoute: typeof DashboardGatewaysGatewayIdIndexRouteImport
      parentRoute: typeof DashboardGatewaysGatewayIdRouteRoute
    }
    '/dashboard/gateways/$gatewayId/settings': {
      id: '/dashboard/gateways/$gatewayId/settings'
      path: '/settings'
      fullPath: '/dashboard/gateways/$gatewayId/settings'
      preLoaderRoute: typeof DashboardGatewaysGatewayIdSettingsRouteImport
      parentRoute: typeof DashboardGatewaysGatewayIdRouteRoute
    }
    '/dashboard/gateways/$gatewayId/sessions/': {
      id: '/dashboard/gateways/$gatewayId/sessions/'
      path: '/sessions'
      fullPath: '/dashboard/gateways/$gatewayId/sessions/'
      preLoaderRoute: typeof DashboardGatewaysGatewayIdSessionsIndexRouteImport
      parentRoute: typeof DashboardGatewaysGatewayIdRouteRoute
    }
    '/dashboard/gateways/$gatewayId_/sessions/$sessionKey': {
      id: '/dashboard/gateways/$gatewayId_/sessions/$sessionKey'
      path: '/gateways/$gatewayId/sessions/$sessionKey'
      fullPath: '/dashboard/gateways/$gatewayId/sessions/$sessionKey'
      preLoaderRoute: typeof DashboardGatewaysGatewayIdSessionsSessionKeyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardGatewaysGatewayIdRouteRouteChildren {
  DashboardGatewaysGatewayIdSettingsRoute: typeof DashboardGatewaysGatewayIdSettingsRoute
  DashboardGatewaysGatewayIdIndexRoute: typeof DashboardGatewaysGatewayIdIndexRoute
  DashboardGatewaysGatewayIdSessionsIndexRoute: typeof DashboardGatewaysGatewayIdSessionsIndexRoute
}

const DashboardGatewaysGatewayIdRouteRouteChildren: DashboardGatewaysGatewayIdRouteRouteChildren =
  {
    DashboardGatewaysGatewayIdSettingsRoute:
      DashboardGatewaysGatewayIdSettingsRoute,
    DashboardGatewaysGatewayIdIndexRoute: DashboardGatewaysGatewayIdIndexRoute,
    DashboardGatewaysGatewayIdSessionsIndexRoute:
      DashboardGatewaysGatewayIdSessionsIndexRoute,
  }

const DashboardGatewaysGatewayIdRouteRouteWithChildren =
  DashboardGatewaysGatewayIdRouteRoute._addFileChildren(
    DashboardGatewaysGatewayIdRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardGatewaysGatewayIdRouteRoute: typeof DashboardGatewaysGatewayIdRouteRouteWithChildren
  DashboardGatewaysIndexRoute: typeof DashboardGatewaysIndexRoute
  DashboardLogsIndexRoute: typeof DashboardLogsIndexRoute
  DashboardGatewaysGatewayIdSessionsSessionKeyRoute: typeof DashboardGatewaysGatewayIdSessionsSessionKeyRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardGatewaysGatewayIdRouteRoute:
    DashboardGatewaysGatewayIdRouteRouteWithChildren,
  DashboardGatewaysIndexRoute: DashboardGatewaysIndexRoute,
  DashboardLogsIndexRoute: DashboardLogsIndexRoute,
  DashboardGatewaysGatewayIdSessionsSessionKeyRoute:
    DashboardGatewaysGatewayIdSessionsSessionKeyRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
