/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardLogsIndexRouteImport } from './routes/dashboard/logs/index'
import { Route as DashboardGatewaysIndexRouteImport } from './routes/dashboard/gateways/index'
import { Route as DashboardGatewaysGatewayIdIndexRouteImport } from './routes/dashboard/gateways/$gatewayId/index'
import { Route as DashboardGatewaysGatewayIdChatRouteImport } from './routes/dashboard/gateways/$gatewayId/chat'
import { Route as DashboardGatewaysGatewayIdSessionsSessionKeyRouteImport } from './routes/dashboard/gateways/$gatewayId/sessions/$sessionKey'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLogsIndexRoute = DashboardLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGatewaysIndexRoute = DashboardGatewaysIndexRouteImport.update({
  id: '/gateways/',
  path: '/gateways/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGatewaysGatewayIdIndexRoute =
  DashboardGatewaysGatewayIdIndexRouteImport.update({
    id: '/gateways/$gatewayId/',
    path: '/gateways/$gatewayId/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardGatewaysGatewayIdChatRoute =
  DashboardGatewaysGatewayIdChatRouteImport.update({
    id: '/gateways/$gatewayId/chat',
    path: '/gateways/$gatewayId/chat',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardGatewaysGatewayIdSessionsSessionKeyRoute =
  DashboardGatewaysGatewayIdSessionsSessionKeyRouteImport.update({
    id: '/gateways/$gatewayId/sessions/$sessionKey',
    path: '/gateways/$gatewayId/sessions/$sessionKey',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/gateways/': typeof DashboardGatewaysIndexRoute
  '/dashboard/logs/': typeof DashboardLogsIndexRoute
  '/dashboard/gateways/$gatewayId/chat': typeof DashboardGatewaysGatewayIdChatRoute
  '/dashboard/gateways/$gatewayId/': typeof DashboardGatewaysGatewayIdIndexRoute
  '/dashboard/gateways/$gatewayId/sessions/$sessionKey': typeof DashboardGatewaysGatewayIdSessionsSessionKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/gateways': typeof DashboardGatewaysIndexRoute
  '/dashboard/logs': typeof DashboardLogsIndexRoute
  '/dashboard/gateways/$gatewayId/chat': typeof DashboardGatewaysGatewayIdChatRoute
  '/dashboard/gateways/$gatewayId': typeof DashboardGatewaysGatewayIdIndexRoute
  '/dashboard/gateways/$gatewayId/sessions/$sessionKey': typeof DashboardGatewaysGatewayIdSessionsSessionKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/gateways/': typeof DashboardGatewaysIndexRoute
  '/dashboard/logs/': typeof DashboardLogsIndexRoute
  '/dashboard/gateways/$gatewayId/chat': typeof DashboardGatewaysGatewayIdChatRoute
  '/dashboard/gateways/$gatewayId/': typeof DashboardGatewaysGatewayIdIndexRoute
  '/dashboard/gateways/$gatewayId/sessions/$sessionKey': typeof DashboardGatewaysGatewayIdSessionsSessionKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/gateways/'
    | '/dashboard/logs/'
    | '/dashboard/gateways/$gatewayId/chat'
    | '/dashboard/gateways/$gatewayId/'
    | '/dashboard/gateways/$gatewayId/sessions/$sessionKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/gateways'
    | '/dashboard/logs'
    | '/dashboard/gateways/$gatewayId/chat'
    | '/dashboard/gateways/$gatewayId'
    | '/dashboard/gateways/$gatewayId/sessions/$sessionKey'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/gateways/'
    | '/dashboard/logs/'
    | '/dashboard/gateways/$gatewayId/chat'
    | '/dashboard/gateways/$gatewayId/'
    | '/dashboard/gateways/$gatewayId/sessions/$sessionKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/logs/': {
      id: '/dashboard/logs/'
      path: '/logs'
      fullPath: '/dashboard/logs/'
      preLoaderRoute: typeof DashboardLogsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/gateways/': {
      id: '/dashboard/gateways/'
      path: '/gateways'
      fullPath: '/dashboard/gateways/'
      preLoaderRoute: typeof DashboardGatewaysIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/gateways/$gatewayId/': {
      id: '/dashboard/gateways/$gatewayId/'
      path: '/gateways/$gatewayId'
      fullPath: '/dashboard/gateways/$gatewayId/'
      preLoaderRoute: typeof DashboardGatewaysGatewayIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/gateways/$gatewayId/chat': {
      id: '/dashboard/gateways/$gatewayId/chat'
      path: '/gateways/$gatewayId/chat'
      fullPath: '/dashboard/gateways/$gatewayId/chat'
      preLoaderRoute: typeof DashboardGatewaysGatewayIdChatRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/gateways/$gatewayId/sessions/$sessionKey': {
      id: '/dashboard/gateways/$gatewayId/sessions/$sessionKey'
      path: '/gateways/$gatewayId/sessions/$sessionKey'
      fullPath: '/dashboard/gateways/$gatewayId/sessions/$sessionKey'
      preLoaderRoute: typeof DashboardGatewaysGatewayIdSessionsSessionKeyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardGatewaysIndexRoute: typeof DashboardGatewaysIndexRoute
  DashboardLogsIndexRoute: typeof DashboardLogsIndexRoute
  DashboardGatewaysGatewayIdChatRoute: typeof DashboardGatewaysGatewayIdChatRoute
  DashboardGatewaysGatewayIdIndexRoute: typeof DashboardGatewaysGatewayIdIndexRoute
  DashboardGatewaysGatewayIdSessionsSessionKeyRoute: typeof DashboardGatewaysGatewayIdSessionsSessionKeyRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardGatewaysIndexRoute: DashboardGatewaysIndexRoute,
  DashboardLogsIndexRoute: DashboardLogsIndexRoute,
  DashboardGatewaysGatewayIdChatRoute: DashboardGatewaysGatewayIdChatRoute,
  DashboardGatewaysGatewayIdIndexRoute: DashboardGatewaysGatewayIdIndexRoute,
  DashboardGatewaysGatewayIdSessionsSessionKeyRoute:
    DashboardGatewaysGatewayIdSessionsSessionKeyRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
